/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static interfaces.Menu.escritorio;
import java.awt.Dimension;
import java.util.ArrayList;
import metodos.Placeholder;

/**
 *
 * @author jsoto
 */
public class AdministrarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdministrarUsuario
     */
    Placeholder placeholder;
    ArrayList<String> listat, listae;

    public AdministrarUsuario() {
        initComponents();
        listat = new ArrayList<>();
        listae = new ArrayList<>();
        cargar_datos();
        placeholder_txt();
        cb_estado.setVisible(false);
        llenar_combos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupocheck = new javax.swing.ButtonGroup();
        label_title = new javax.swing.JLabel();
        label_subtitle = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apaterno = new javax.swing.JTextField();
        txt_amaterno = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        txt_user = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        cb_tipo = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        cb_estado = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono.png"))); // NOI18N

        label_title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("Administrar Usuarios/ Crear Nuevo");

        label_subtitle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_subtitle.setText("Datos:");

        txt_nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_apaterno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_amaterno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_celular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_user.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_password.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cb_tipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_guardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/save.png"))); // NOI18N
        btn_guardar.setText("Guardar");

        btn_regresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/back.png"))); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        cb_estado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_subtitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_password)
                    .addComponent(cb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_user)
                    .addComponent(txt_celular)
                    .addComponent(txt_amaterno)
                    .addComponent(txt_apaterno)
                    .addComponent(txt_nombre)
                    .addComponent(cb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_apaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_amaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_regresar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        ListarUsuarios lu = new ListarUsuarios();
        escritorio.add(lu);
        Dimension escritorio_size = escritorio.getSize();
        Dimension lu_size = lu.getSize();
        lu.setLocation((escritorio_size.width - lu_size.width) / 2, (escritorio_size.height - lu_size.height) / 2);
        lu.show();
        dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_regresar;
    public static javax.swing.JComboBox<String> cb_estado;
    public static javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.ButtonGroup grupocheck;
    private javax.swing.JLabel label_subtitle;
    private javax.swing.JLabel label_title;
    public static javax.swing.JTextField txt_amaterno;
    public static javax.swing.JTextField txt_apaterno;
    public static javax.swing.JTextField txt_celular;
    public static javax.swing.JTextField txt_nombre;
    public static javax.swing.JPasswordField txt_password;
    public static javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    private void placeholder_txt() {
        placeholder = new Placeholder("Ingrese su nombre", txt_nombre);
        placeholder = new Placeholder("Ingrese su Apellido Paterno", txt_apaterno);
        placeholder = new Placeholder("Ingrese su Apellido Materno", txt_amaterno);
        placeholder = new Placeholder("Ingrese su numero de celular", txt_celular);
        placeholder = new Placeholder("Ingrese su nombre de usuario", txt_user);
        placeholder = new Placeholder("Ingrese su contraseña", txt_password);
    }

    private void cargar_datos() {
        listat.add("<-SELECCIONAR->");
        listat.add("Administrador");
        listat.add("Usuario");
        listae.add("<-SELECCIONAR->");
        listae.add("Activo");
        listae.add("Inactivo");
    }

    private void llenar_combos() {
        cb_tipo.removeAllItems();
        cb_estado.removeAllItems();
        for (int i = 0; i < listat.size(); i++) {
            cb_tipo.addItem(listat.get(i));
        }
        for (int i = 0; i < listae.size(); i++) {
            cb_estado.addItem(listae.get(i));
        }
    }
}
