/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import estilos.GestionCeldas;
import estilos.GestionEncabezadoTabla;
import estilos.ModeloTablaLU;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import metodos.Placeholder;
import objetos.Datos_Clientes;

/**
 *
 * @author Cristhian
 */
public class Clientes extends javax.swing.JInternalFrame {

    ModeloTablaLU dtm_cliente;
    Placeholder placeholder;
    ArrayList<Datos_Clientes> listac;
    Datos_Clientes additem;
    TableRowSorter trs;
    RowSorter<TableModel> sorter;
    int colum = 0;

    public Clientes() {
        initComponents();
        dtm_cliente = new ModeloTablaLU();
        listac = new ArrayList<>();
        sorter = new TableRowSorter<TableModel>(dtm_cliente);
        cargar_datos();
        tbl_datos.setModel(dtm_cliente);
        tbl_datos.setRowSorter(sorter);
        placeholder = new Placeholder("Ingrese el apellido para iniciar el filtrado", txt_buscar);
        tabla_cargada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        label_subtitle = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        cb_orden = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbl_datosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_datos);

        label_subtitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_subtitle.setForeground(new java.awt.Color(255, 255, 255));
        label_subtitle.setText("Ordenar Por:");

        txt_buscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });

        cb_orden.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_orden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "DNI", "APELLIDOS", "NOMBRES", "DIRECCIÓN ", "DISPOSITIVOS", "FECHA DE CONTRATO" }));
        cb_orden.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ordenItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_subtitle)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_datosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_datosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_datosKeyTyped

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
        txt_buscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar.getText(), 2));
            }
        });
        trs = new TableRowSorter(dtm_cliente);
        tbl_datos.setRowSorter(trs);
    }//GEN-LAST:event_txt_buscarKeyTyped

    private void cb_ordenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ordenItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            colum = cb_orden.getSelectedIndex();
            if (colum >= 0) {
                if (colum > 4) {
                    tbl_datos.getRowSorter().toggleSortOrder(colum+3);
                } else {
                    tbl_datos.getRowSorter().toggleSortOrder(colum);
                }
            }
        }
    }//GEN-LAST:event_cb_ordenItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_orden;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_subtitle;
    private javax.swing.JTable tbl_datos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    private void cabecera() {
        dtm_cliente.addColumn("ID");
        dtm_cliente.addColumn("DNI");
        dtm_cliente.addColumn("APELLIDOS");
        dtm_cliente.addColumn("NOMBRES");
        dtm_cliente.addColumn("DIRECCIÓN");
        dtm_cliente.addColumn("CELULAR");
        dtm_cliente.addColumn("ESTADO");
        dtm_cliente.addColumn("IP");
        dtm_cliente.addColumn("DISPOSITIVOS");
        dtm_cliente.addColumn("FECHA DE CONTRATO");
    }

    private void cargar_datos() {
        additem = new Datos_Clientes("001", "74803992", "Soto Navarro", "Cristhian Arturo", "Nomara", "976452348","Activo","12.168.6.104","5","12/12/12");
        listac.add(additem);
        additem = new Datos_Clientes("002", "80334200", "Navarro Castro", "Maria Carolina", "Fatima", "966612995","Inactivo","12.168.6.100","1","14/05/12");
        listac.add(additem);
        additem = new Datos_Clientes("003", "03478775", "Soto Navarro", "Jesus Ricardo", "Nomara", "976452348","Activo","12.168.6.10","3","10/10/12");
        listac.add(additem);
        additem = new Datos_Clientes("004", "74803993", "Soto Navarro", "Jhon Alex", "Miraflores", "950234204","Suspendido","12.168.6.90","6","14/04/12");
        listac.add(additem);
    }

    private void llenar_celdas() {
        //copiar datos de la lista a la tabla
        String data[] = new String[10];
        for (int i = 0; i < listac.size(); i++) {
            data[0] = listac.get(i).getId();
            data[1] = listac.get(i).getDni();
            data[2] = listac.get(i).getApellidos();
            data[3] = listac.get(i).getNombres();
            data[4] = listac.get(i).getDireccion();
            data[5] = listac.get(i).getCelular();
            data[6] = listac.get(i).getEstado();
            data[7] = listac.get(i).getIp();
            data[8] = listac.get(i).getDispositivos();
            data[9] = listac.get(i).getFecha_contrato();
            dtm_cliente.addRow(data);
        }
    }

    private void tabla_cargada() {
        //llamar la cabecera de la tabla
        cabecera();
        //llenado de celdas
        llenar_celdas();
        //estilo de celda
        tbl_datos.getColumnModel().getColumn(0).setCellRenderer(new GestionCeldas("numerico"));
        tbl_datos.getColumnModel().getColumn(1).setCellRenderer(new GestionCeldas("numerico"));
        tbl_datos.getColumnModel().getColumn(2).setCellRenderer(new GestionCeldas("texto"));
        tbl_datos.getColumnModel().getColumn(3).setCellRenderer(new GestionCeldas("texto"));
        tbl_datos.getColumnModel().getColumn(4).setCellRenderer(new GestionCeldas("texto"));
        tbl_datos.getColumnModel().getColumn(5).setCellRenderer(new GestionCeldas("numerico"));
        tbl_datos.getColumnModel().getColumn(6).setCellRenderer(new GestionCeldas("texto"));
        tbl_datos.getColumnModel().getColumn(7).setCellRenderer(new GestionCeldas("numerico"));
        tbl_datos.getColumnModel().getColumn(8).setCellRenderer(new GestionCeldas("numerico"));
        tbl_datos.getColumnModel().getColumn(9).setCellRenderer(new GestionCeldas("numerico"));
        //reordenar la tabla
        tbl_datos.getTableHeader().setReorderingAllowed(false);
        //alto de las celdas
        tbl_datos.setRowHeight(30);
        //Ancho de las celdas
        tbl_datos.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbl_datos.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbl_datos.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbl_datos.getColumnModel().getColumn(7).setPreferredWidth(150);
        tbl_datos.getColumnModel().getColumn(9).setPreferredWidth(150);
        //estilos de cabecera
        JTableHeader jTableHeader = tbl_datos.getTableHeader();
        jTableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        tbl_datos.setTableHeader(jTableHeader);
    }
}
