/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import estilos.EstiloEncabezadoTCobro;
import estilos.GestionCeldas;
import estilos.ModeloTabla;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import metodos.Placeholder;
import objetos.Cobros_clientes;

/**
 *
 * @author Cristhian
 */
public final class Cobros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cobros
     */
    ModeloTabla modelo;
    TableRowSorter trs;
    ArrayList<Cobros_clientes> listac;
    Cobros_clientes additem;
    Placeholder placeholder;

    public Cobros() {
        initComponents();
        modelo = new ModeloTabla();
        listac = new ArrayList<>();
        cargar_datos();
        tabla_datos.setModel(modelo);
        placeholder = new Placeholder("Ingrese datos para iniciar el filtrado", txt_buscar);
        tabla_cargada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cobros");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/payment.png"))); // NOI18N

        label_title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("REGISTRO DE COBROS");

        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_datosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_datos);

        txt_buscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/search.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(500, 500, 500))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
        txt_buscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                //trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar.getText(), 0));
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar.getText(), 1));
                //trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar.getText(), 2));
            }
        });
        trs = new TableRowSorter(modelo);
        tabla_datos.setRowSorter(trs);
    }//GEN-LAST:event_txt_buscarKeyTyped

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tabla_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_datosMouseClicked

        verificar_completa();

    }//GEN-LAST:event_tabla_datosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_title;
    private javax.swing.JTable tabla_datos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
    private void cabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("APELLIDOS");
        modelo.addColumn("NOMBRES");
        modelo.addColumn("ESTADO");
        modelo.addColumn("PERIODO");
        modelo.addColumn("FECHA");
        modelo.addColumn("DESCRIPCIÓN");
        modelo.addColumn("PLAN S/.");
        modelo.addColumn("DEUDA");
        modelo.addColumn("PAGO");
        modelo.addColumn("MONTO");
    }

    private void cargar_datos() {
        additem = new Cobros_clientes("001", "74803992", "Soto Navarro", "Cristhian Arturo", "Activo", "Mayo", "10-06-2020", "mensualidad de mayo", "50", "120", "");
        listac.add(additem);
        additem = new Cobros_clientes("002", "80334200", "Navarro Castro", "María Carolina", "Inactivo", "Junio", "11-07-2020", "mensualidad de Junio", "40", "80", "");
        listac.add(additem);
        additem = new Cobros_clientes("003", "74803993", "Soto Navarro", "Jhon Alex", "Activo", "Junio", "10-07-2020", "mensualidad de Junio", "50", "50", "");
        listac.add(additem);
        additem = new Cobros_clientes("004", "03478775", "Soto Navarro", "Jesús Ricardo", "Activo", "Julio", "10-08-2020", "mensualidad de mayo", "30", "90", "");
        listac.add(additem);
    }

    private void llenar_celdas() {
        //copiar datos de la lista a la tabla
        String data[] = new String[12];
        for (int i = 0; i < listac.size(); i++) {
            data[0] = listac.get(i).getId();
            data[1] = listac.get(i).getDni();
            data[2] = listac.get(i).getApellidos();
            data[3] = listac.get(i).getNombres();
            data[4] = listac.get(i).getEstado();
            data[5] = listac.get(i).getPeriodo();
            data[6] = listac.get(i).getFecha();
            data[7] = listac.get(i).getDescripcion();
            data[8] = listac.get(i).getPlan();
            data[9] = listac.get(i).getDeuda();
            data[11] = listac.get(i).getMonto();
            modelo.addRow(data);
        }
    }

    private void tabla_cargada() {
        //datos de cabecera
        cabecera();
        //llenado de celdas
        llenar_celdas();
        addCheckBox(10, tabla_datos);
        //estilo de celda
        tabla_datos.getColumnModel().getColumn(0).setCellRenderer(new GestionCeldas("numerico"));
        tabla_datos.getColumnModel().getColumn(1).setCellRenderer(new GestionCeldas("numerico"));
        tabla_datos.getColumnModel().getColumn(2).setCellRenderer(new GestionCeldas("texto"));
        tabla_datos.getColumnModel().getColumn(3).setCellRenderer(new GestionCeldas("texto"));
        tabla_datos.getColumnModel().getColumn(4).setCellRenderer(new GestionCeldas("texto"));
        tabla_datos.getColumnModel().getColumn(5).setCellRenderer(new GestionCeldas("texto"));
        tabla_datos.getColumnModel().getColumn(6).setCellRenderer(new GestionCeldas("numerico"));
        tabla_datos.getColumnModel().getColumn(7).setCellRenderer(new GestionCeldas("texto"));
        tabla_datos.getColumnModel().getColumn(8).setCellRenderer(new GestionCeldas("numerico"));
        tabla_datos.getColumnModel().getColumn(9).setCellRenderer(new GestionCeldas("numerico"));
        //tabla_datos.getColumnModel().getColumn(10).setCellRenderer(new GestionCeldas("chk_box"));
        tabla_datos.getColumnModel().getColumn(11).setCellRenderer(new GestionCeldas("numerico"));
        //reordenar la tabla
        tabla_datos.getTableHeader().setReorderingAllowed(false);
        //alto de las celdas
        tabla_datos.setRowHeight(30);
        //Ancho de las celdas
        tabla_datos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabla_datos.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabla_datos.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabla_datos.getColumnModel().getColumn(3).setPreferredWidth(200);
        tabla_datos.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabla_datos.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabla_datos.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabla_datos.getColumnModel().getColumn(7).setPreferredWidth(200);
        //estilos de cabecera
        JTableHeader jTableHeader = tabla_datos.getTableHeader();
        jTableHeader.setDefaultRenderer(new EstiloEncabezadoTCobro());
        tabla_datos.setTableHeader(jTableHeader);

    }

    public void addCheckBox(int column, JTable table) {
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }

    public boolean IsSelected(int row, int column, JTable table) {
        return table.getValueAt(row, column) != null;
    }

    public void verificar_completa() {
        for (int i = 0; i < tabla_datos.getRowCount(); i++) {
            if (IsSelected(i, 10, tabla_datos)) {
                modelo.setValueAt(listac.get(i).getPlan(), i, 11);
            }//else{
            //modelo.setValueAt("", i, 11);
            //modelo.fireTableDataChanged();
            //System.out.println("hola");
            //}
        }
    }
}
