/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Cristhian
 */
public class Estadisticas extends javax.swing.JInternalFrame {

    ArrayList<String> meses;
    ArrayList<Integer> cantidad;
    ArrayList<Integer> gastos;

    public Estadisticas() {
        initComponents();
        meses = new ArrayList<>();
        cantidad = new ArrayList<>();
        gastos = new ArrayList<>();
        cargar_datos();
        graficar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Graficas Estadisticas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/estadisticas.png"))); // NOI18N

        jLabel1.setText("Seleccione el Año:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(665, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private void cargar_datos() {
        meses.add("Enero");
        meses.add("Febrero");
        meses.add("Marzo");
        meses.add("Abril");
        meses.add("Mayo");
        meses.add("Junio");
        meses.add("Julio");
        meses.add("Agosto");
        meses.add("Septiembre");
        meses.add("Octubre");
        meses.add("Noviembre");
        meses.add("Diciembre");
        cantidad.add(900);
        cantidad.add(840);
        cantidad.add(1000);
        cantidad.add(700);
        cantidad.add(630);
        cantidad.add(800);
        cantidad.add(1020);
        cantidad.add(1080);
        cantidad.add(700);
        cantidad.add(1000);
        cantidad.add(1800);
        cantidad.add(2000);
        gastos.add(535);
        gastos.add(635);
        gastos.add(935);
        gastos.add(535);
        gastos.add(335);
        gastos.add(435);
        gastos.add(935);
        gastos.add(1035);
        gastos.add(535);
        gastos.add(235);
        gastos.add(535);
        gastos.add(735);
    }

    private void graficar() {
        DefaultCategoryDataset dataset = (DefaultCategoryDataset) datos_estadisticos();
        JFreeChart freeChart = ChartFactory.createBarChart3D("", "Meses", "Cantidad Recaudada", dataset, PlotOrientation.VERTICAL, true, true, false);
        //JFreeChart freeChart = ChartFactory.createStackedBarChart3D("Estadisticas Anuales", "Meses", "Cantidad Recaudada", dataset, PlotOrientation.VERTICAL, true, true, false);
        freeChart.setBackgroundPaint(Color.WHITE);
        //obtiene la referencia de su plot
        CategoryPlot plot = freeChart.getCategoryPlot();
        //dibuja con el plot el color de fondo
        plot.setBackgroundPaint(Color.BLACK);
        plot.setRangeGridlinePaint(Color.BLUE);
        //establece la posicion en el eje de las x
        plot.setDomainAxisLocation(AxisLocation.BOTTOM_OR_RIGHT);
        ChartPanel panel = new ChartPanel(freeChart);       
        this.setContentPane(panel);
      
    }

    private CategoryDataset datos_estadisticos() {
        //entradas y salidas
        final String cobro = "Cobro";
        final String gasto = "Gasto";
        final String ganancia = "Ganancia";
        //creamos el dataset
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        //se agregan los valores
        for (int i = 0; i < cantidad.size(); i++) {
            dataset.setValue(cantidad.get(i), cobro, meses.get(i));
        }
        for (int i = 0; i < gastos.size(); i++) {
            dataset.setValue(gastos.get(i), gasto, meses.get(i));
        }
        for (int i = 0; i < gastos.size(); i++) {
            dataset.setValue(cantidad.get(i) - gastos.get(i), ganancia, meses.get(i));
        }
        return dataset;
    }
}
