/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import metodos.Placeholder;

/**
 *
 * @author Cristhian
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    int count=0;
    Placeholder placeholder;
    
    public Login() {
        initComponents();
        //mostrar imagen de fondo
        ImageIcon fondo=new ImageIcon("src/recursos/fondo_login.jpg");
        Icon icon=new ImageIcon(fondo.getImage().getScaledInstance(label_fondo.getWidth(), label_fondo.getHeight(), Image.SCALE_DEFAULT));
        label_fondo.setIcon(icon);
        placeholder=new Placeholder("Nombre de Usuario", txt_user);
        placeholder=new Placeholder("Ingrese Contraseña", txt_password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_acceder = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        label_fondo = new javax.swing.JLabel();

        setTitle("Login");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(350, 430));
        getContentPane().setLayout(null);

        label_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_title.setText("Login");
        getContentPane().add(label_title);
        label_title.setBounds(61, 76, 64, 32);

        label_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/user.png"))); // NOI18N
        getContentPane().add(label_user);
        label_user.setBounds(61, 134, 48, 48);

        txt_user.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txt_user);
        txt_user.setBounds(127, 143, 167, 30);

        label_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/password.png"))); // NOI18N
        getContentPane().add(label_password);
        label_password.setBounds(61, 200, 48, 48);

        txt_password.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        getContentPane().add(txt_password);
        txt_password.setBounds(130, 210, 167, 30);

        btn_acceder.setBackground(new java.awt.Color(102, 255, 102));
        btn_acceder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/accept.png"))); // NOI18N
        btn_acceder.setText("Acceder");
        btn_acceder.setEnabled(false);
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });
        getContentPane().add(btn_acceder);
        btn_acceder.setBounds(70, 280, 110, 29);

        btn_salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/out.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir);
        btn_salir.setBounds(190, 280, 110, 29);

        label_fondo.setPreferredSize(new java.awt.Dimension(350, 430));
        getContentPane().add(label_fondo);
        label_fondo.setBounds(0, 0, 350, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed
        acceder();
    }//GEN-LAST:event_btn_accederActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            count++;
            if(txt_user.getText().length()>0 && txt_password.getText().length()>0 && count<2){
                verifica();
            }else{
                acceder();
            }
        }
    }//GEN-LAST:event_txt_passwordKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acceder;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_user;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    private void verifica(){
        String user="admin", password="admin";
        if(user.equals(txt_user.getText()) && password.equals(txt_password.getText())){
            btn_acceder.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "Credenciales Incorrectas");
            txt_user.setText("");
            txt_password.setText("");
            txt_user.requestFocus();
        }
    }
    
    private void acceder(){
        this.dispose();
        interfaces.Menu.menu.setVisible(true);
    }
}
