/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Dimension;

/**
 *
 * @author Cristhian
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        login_cargado();
        menu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        m_modulos = new javax.swing.JMenu();
        m_tablas = new javax.swing.JMenu();
        m_movimientos = new javax.swing.JMenu();
        m_reportes = new javax.swing.JMenu();
        m_utilitarios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        m_modulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/modules.png"))); // NOI18N
        m_modulos.setText("Modulos");
        m_modulos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_modulos);

        m_tablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/tables.png"))); // NOI18N
        m_tablas.setText("Tablas");
        m_tablas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_tablas);

        m_movimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/movements.png"))); // NOI18N
        m_movimientos.setText("Movimientos");
        m_movimientos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_movimientos);

        m_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/reports.png"))); // NOI18N
        m_reportes.setText("Reportes");
        m_reportes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_reportes);

        m_utilitarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/settings.png"))); // NOI18N
        m_utilitarios.setText("Utilitarios");
        m_utilitarios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.add(m_utilitarios);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu m_modulos;
    private javax.swing.JMenu m_movimientos;
    private javax.swing.JMenu m_reportes;
    private javax.swing.JMenu m_tablas;
    private javax.swing.JMenu m_utilitarios;
    public static javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables

     private void login_cargado(){
        Login cargar_login=new Login();
        escritorio.add(cargar_login);
        Dimension escritorio_size=escritorio.getSize();
        Dimension login_size=cargar_login.getSize();
        cargar_login.setLocation((escritorio_size.width+login_size.width)/2, (escritorio_size.height+login_size.height)/7);
        cargar_login.show();
    }
}
