/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import estilos.GestionCeldas;
import estilos.GestionEncabezadoTabla;
import estilos.ModeloTablaLU;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import metodos.Placeholder;
import objetos.Record_cliente;

/**
 *
 * @author Cristhian
 */
public class RecordCliente extends javax.swing.JInternalFrame {

    ModeloTablaLU dtm_record;
    Placeholder placeholder;
    ArrayList<Record_cliente> listar;
    Record_cliente additem;
    TableRowSorter trs;
    RowSorter<TableModel> sorter;

    public RecordCliente() {
        initComponents();
        dtm_record = new ModeloTablaLU();
        listar = new ArrayList<>();
        sorter = new TableRowSorter<TableModel>(dtm_record);
        cargar_datos();
        llenar_combo();
        tbl_datos.setModel(dtm_record);
        tbl_datos.setRowSorter(sorter);
        placeholder = new Placeholder("Ingrese el apellido para iniciar el filtrado", txt_buscar);
        tabla_cargada();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        label_subtitle = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        cb_orden = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icono.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Recòrd de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbl_datosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_datos);

        label_subtitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label_subtitle.setForeground(new java.awt.Color(255, 255, 255));
        label_subtitle.setText("Ordenar Por:");

        txt_buscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });

        cb_orden.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_orden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_orden.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ordenItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_subtitle)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_datosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_datosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_datosKeyTyped

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
        txt_buscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txt_buscar.getText(), 1));
            }
        });
        trs = new TableRowSorter(dtm_record);
        tbl_datos.setRowSorter(trs);
    }//GEN-LAST:event_txt_buscarKeyTyped

    private void cb_ordenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ordenItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int i = cb_orden.getSelectedIndex();
            if (i >= 0) {
                if (i > 2) {
                    //tbl_datos.getRowSorter().toggleSortOrder(i + 1);
                    System.out.println(i+1);
                } else {
                    //tbl_datos.getRowSorter().toggleSortOrder(i);
                    System.out.println(i);
                }
            }
            
        }
    }//GEN-LAST:event_cb_ordenItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_orden;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_subtitle;
    private javax.swing.JTable tbl_datos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    private void cabecera() {
        dtm_record.addColumn("ID");
        dtm_record.addColumn("APELLIDOS");
        dtm_record.addColumn("NOMBRES");
        dtm_record.addColumn("ESTADO");
        dtm_record.addColumn("DEUDA");
        dtm_record.addColumn("RECÒRD");
    }

    private void llenar_combo() {
        cb_orden.removeAllItems();
        cb_orden.addItem("ID");
        cb_orden.addItem("APELLIDOS");
        cb_orden.addItem("NOMBRES");
        cb_orden.addItem("DEUDA");
        cb_orden.addItem("RÈCORD");
    }

    private void cargar_datos() {
        additem = new Record_cliente("001", "Soto Navarro", "Cristhian Arturo", "Activo", "0", "Buen Cliente");
        listar.add(additem);
        additem = new Record_cliente("002", "Zoto Navarro", "Angie Carolina", "Activo", "100", "Moroso");
        listar.add(additem);
        additem = new Record_cliente("003", "Navarro Castro", "Maria Caroilina", "Inactivo", "0", "Buen Cliente");
        listar.add(additem);
        additem = new Record_cliente("004", "Alvarez Costa", "Jhon Alex", "Activo", "50", "Moroso");
        listar.add(additem);
    }

    private void llenar_celdas() {
        //copiar datos de la lista a la tabla
        String data[] = new String[6];
        for (int i = 0; i < listar.size(); i++) {
            data[0] = listar.get(i).getId();
            data[1] = listar.get(i).getApellidos();
            data[2] = listar.get(i).getNombres();
            data[3] = listar.get(i).getEstado();
            data[4] = listar.get(i).getDeuda();
            data[5] = listar.get(i).getRecord();
            dtm_record.addRow(data);
        }
    }

    private void tabla_cargada() {
        //llamar la cabecera de la tabla
        cabecera();
        //llenado de celdas
        llenar_celdas();
        //estilo de celda
        tbl_datos.getColumnModel().getColumn(0).setCellRenderer(new GestionCeldas("numerico"));
        tbl_datos.getColumnModel().getColumn(1).setCellRenderer(new GestionCeldas("texto"));
        tbl_datos.getColumnModel().getColumn(2).setCellRenderer(new GestionCeldas("texto"));
        tbl_datos.getColumnModel().getColumn(3).setCellRenderer(new GestionCeldas("texto"));
        tbl_datos.getColumnModel().getColumn(4).setCellRenderer(new GestionCeldas("numerico"));
        tbl_datos.getColumnModel().getColumn(5).setCellRenderer(new GestionCeldas("texto"));
        //reordenar la tabla
        tbl_datos.getTableHeader().setReorderingAllowed(false);
        //alto de las celdas
        tbl_datos.setRowHeight(30);
        //Ancho de las celdas
        tbl_datos.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbl_datos.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbl_datos.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbl_datos.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbl_datos.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbl_datos.getColumnModel().getColumn(5).setPreferredWidth(250);
        //estilos de cabecera
        JTableHeader jTableHeader = tbl_datos.getTableHeader();
        jTableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        tbl_datos.setTableHeader(jTableHeader);
    }
}
